### ISSUE TITLE
Design System Components Unable to Receive Sprinkles Token Props

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/jung-ui#10]
## 📌 Issue

- The design system components, such as the Button component, are unable to receive the Sprinkles token props, which are used to apply styles to the components.

<br/>

## ☑️ To-do

- [x] Modify the Box component to allow the Sprinkles token props to be passed down to other design system components.
- [x] Update the Button component and other design system components to accept the Sprinkles token props.
- [x] Ensure that the Sprinkles token props are correctly applied to the design system components.
- [x] Verify that the design system components are now able to receive and utilize the Sprinkles token props.
