### ISSUE TITLE
✨ Implement Box component and atoms utility

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/jung-ui#4]
## 📌 Issue

- Implement Box component and atoms utility

<br/>

## ☑️ To-do

- [x] Implement Box component
- [x] Implement atoms utility function
- [x] Write unit tests for Box component and atoms utility
